title: "Regal Roots: The Grove and Goatery Estate"
description: "A local farm dedicated to sustainable farming practices and community involvement."
baseurl: "/RegalRoots"
url: "https://justaghost.github.io"

# Build settings

# Minimal Mistakes theme settings
author:
  name: "Regal Roots"
  avatar: "/public/images/avatar.png"
  bio: "A local farm dedicated to sustainable farming practices and community involvement."
  location: "Bela Bela"
  email: "info@regalroots.com"
  links:
    - label: "GitHub"
      url: "https://github.com/githubnext/workspace-blank"
    - label: "Twitter"
      url: "https://twitter.com/regalroots"
    - label: "Facebook"
      url: "https://facebook.com/regalroots"

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Products"
    url: "/products/"
  - title: "Contact"
    url: "/contact/"
  - title: "Business Plan"
    url: "/business/business-plan/"
  - title: "Expenses Breakdown"
    url: "/business/expenses-breakdown/"
  - title: "Timelines"
    url: "/business/timelines/"

# Social sharing
twitter_username: "regalroots"
github_username: "githubnext"
