title: "Regal Roots: The Grove and Goatery Estate"
description: "A local farm dedicated to sustainable farming practices and community involvement."
baseurl: "/"
url: "https://justaghost.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
highlighter: rouge

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default"
show_excerpts: true
author:
  name: "Regal Roots"
  avatar: "/RegalRoots/public/images/avatar.png"
  bio: "A local farm dedicated to sustainable farming practices and community involvement."
  location: "Bela Bela"
  email: "info@regalroots.com"
  links:
    - label: "GitHub"
      url: "https://github.com/githubnext/workspace-blank"
    - label: "Twitter"
      url: "https://twitter.com/regalroots"
    - label: "Facebook"
      url: "https://facebook.com/regalroots"

# Navigation
nav:
  - title: "Home"
    url: "/RegalRoots/"  # Include the baseurl
  - title: "About"
    url: "/RegalRoots/about/"
  - title: "Products"
    url: "/RegalRoots/products/"
  - title: "Contact"
    url: "/RegalRoots/contact/"
  - title: "Business Plan"
    url: "/RegalRoots/business/business-plan/"
  - title: "Expenses Breakdown"
    url: "/RegalRoots/business/expenses-breakdown/"
  - title: "Timelines"
    url: "/RegalRoots/business/timelines/"

# Social sharing
twitter_username: "regalroots"
github_username: "githubnext"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

